# Yo Theme for Kitty
# Based on the Helix theme by Michael McClintock <michael.mcclintock@hey.com>
# License: MIT
# https://github.com/mrmcc3/yo-theme-helix

# The basic colors
foreground              #b4b4b4
background              #191919
selection_foreground    #191919
selection_background    #eeeeee

# Cursor colors
cursor                  #b4b4b4
cursor_text_color       #191919

# URL underline color
url_color               #3b9eff

# Kitty window border colors
active_border_color     #eeeeee
inactive_border_color   #484848
bell_border_color       #ec5d5e

# OS Window titlebar colors
wayland_titlebar_color  #191919
macos_titlebar_color    #191919

# Tab bar colors
active_tab_foreground   #191919
active_tab_background   #eeeeee
inactive_tab_foreground #b4b4b4
inactive_tab_background #2a2a2a
tab_bar_background      #191919

# Colors for marks (marked text in the terminal)
mark1_foreground #191919
mark1_background #3b9eff
mark2_foreground #191919
mark2_background #9a5cd0
mark3_foreground #191919
mark3_background #ec5d5e

# The 16 terminal colors

# black
color0   #111111
color8   #606060

# red
color1   #ec5d5e
color9   #ff5a5a

# green
color2   #33b074
color10  #4ade80

# yellow
color3   #ff801f
color11  #ffa348

# blue
color4   #3b9eff
color12  #6eb6ff

# magenta
color5   #9a5cd0
color13  #b77af0

# cyan
color6   #ae8c7e
color14  #c4a593

# white
color7   #b4b4b4
color15  #eeeeee
